# Generated by Django 4.1.7 on 2023-03-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_key',
            field=models.TextField(),
        ),
    ]
