# Generated by Django 4.1.7 on 2023-03-01 23:39

import django.core.validators
from django.db import migrations, models
import update_db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lat_lng_key', models.PositiveBigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[01](900000|[0-8][0-9]{5})[01](1800000|1[0-7][0-9]{5}|0[0-9]{6})')])),
                ('walk_score', models.PositiveSmallIntegerField(validators=[update_db.models.validate_ws_score])),
                ('bike_score', models.PositiveSmallIntegerField(validators=[update_db.models.validate_ws_score])),
                ('transit_score', models.PositiveSmallIntegerField(validators=[update_db.models.validate_ws_score])),
                ('sound_score', models.PositiveSmallIntegerField(validators=[update_db.models.validate_hl_score])),
            ],
        ),
    ]
