# Generated by Django 4.1.7 on 2023-03-02 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='grocery_dist',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='school_dist',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='transit_dist',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='lat_lng_key',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('1[01](900000|[0-8][0-9]{5})[01](1800000|1[0-7][0-9]{5}|0[0-9]{6})')]),
        ),
    ]
