# Generated by Django 4.1.7 on 2023-03-12 23:06

from django.db import migrations, models
import update_db.models


class Migration(migrations.Migration):

    dependencies = [
        ('update_db', '0002_location_grocery_dist_location_school_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='bike_score',
            field=models.PositiveSmallIntegerField(null=True, validators=[update_db.models.validate_ws_score]),
        ),
        migrations.AlterField(
            model_name='location',
            name='sound_score',
            field=models.PositiveSmallIntegerField(null=True, validators=[update_db.models.validate_hl_score]),
        ),
        migrations.AlterField(
            model_name='location',
            name='transit_score',
            field=models.PositiveSmallIntegerField(null=True, validators=[update_db.models.validate_ws_score]),
        ),
        migrations.AlterField(
            model_name='location',
            name='walk_score',
            field=models.PositiveSmallIntegerField(null=True, validators=[update_db.models.validate_ws_score]),
        ),
    ]
